const VOCAB_BANK = [
  { en:"Ambiguous", th:"มีความหมายไม่ชัดเจน", ex:"The instructions were ambiguous.", ex_th:"คำแนะนำกำกวม" },
  { en:"Analogy", th:"การเปรียบเทียบ", ex:"He drew an analogy between a heart and a pump.", ex_th:"เขาเปรียบเทียบหัวใจกับปั๊ม" },
  { en:"Analyze", th:"วิเคราะห์", ex:"We need to analyze the data carefully.", ex_th:"เราต้องวิเคราะห์ข้อมูลอย่างรอบคอบ" },
  { en:"Advocate", th:"สนับสนุน / ผู้สนับสนุน", ex:"She is a strong advocate for education.", ex_th:"เธอเป็นผู้สนับสนุนด้านการศึกษาอย่างแรงกล้า" },
  { en:"Assess", th:"ประเมิน", ex:"The teacher will assess the students' progress.", ex_th:"ครูจะประเมินความก้าวหน้าของนักเรียน" },
  { en:"Assumption", th:"การสมมติฐาน", ex:"His theory is based on a false assumption.", ex_th:"ทฤษฎีของเขาอยู่บนสมมติฐานที่ผิด" },
  { en:"Bias", th:"อคติ", ex:"The article showed a clear bias.", ex_th:"บทความแสดงอคติอย่างชัดเจน" },
  { en:"Clarify", th:"ชี้แจง", ex:"Could you clarify your point?", ex_th:"ช่วยชี้แจงประเด็นของคุณหน่อยได้ไหม" },
  { en:"Coherent", th:"เชื่อมโยงกันอย่างสมเหตุสมผล", ex:"She gave a coherent explanation.", ex_th:"เธออธิบายได้สอดคล้องกัน" },
  { en:"Concept", th:"แนวคิด", ex:"It's a difficult concept to understand.", ex_th:"มันเป็นแนวคิดที่เข้าใจยาก" },
  { en:"Conclusion", th:"บทสรุป", ex:"What conclusion can we draw?", ex_th:"เราสรุปได้ว่าอะไร" },
  { en:"Context", th:"บริบท", ex:"You need to understand the context.", ex_th:"คุณต้องเข้าใจบริบท" },
  { en:"Contradict", th:"ขัดแย้ง", ex:"His statement contradicts the facts.", ex_th:"คำพูดของเขาขัดแย้งกับข้อเท็จจริง" },
  { en:"Criteria", th:"เกณฑ์", ex:"What are the selection criteria?", ex_th:"เกณฑ์การคัดเลือกคืออะไร" },
  { en:"Deduce", th:"สรุปหาเหตุผล", ex:"From the clues, we can deduce the answer.", ex_th:"จากเบาะแส เราอาจสรุปคำตอบได้" },
  { en:"Elaborate", th:"อธิบายอย่างละเอียด", ex:"Could you elaborate on that idea?", ex_th:"ช่วยอธิบายแนวคิดนั้นเพิ่มเติมได้ไหม" },
  { en:"Emphasize", th:"เน้น / ให้ความสำคัญ", ex:"I want to emphasize this point.", ex_th:"ฉันอยากเน้นประเด็นนี้" },
  { en:"Evidence", th:"หลักฐาน", ex:"There is no evidence to support that claim.", ex_th:"ไม่มีหลักฐานสนับสนุนคำกล่าวนั้น" },
  { en:"Explicit", th:"ชัดเจน / ตรงไปตรงมา", ex:"The instructions were explicit.", ex_th:"คำแนะนำชัดเจนดี" },
  { en:"Generalize", th:"สรุปอย่างกว้างๆ", ex:"You can't generalize from one example.", ex_th:"คุณไม่สามารถสรุปจากตัวอย่างเดียวได้" },
  { en:"Hypothesis", th:"สมมติฐาน", ex:"The scientist tested her hypothesis.", ex_th:"นักวิทยาศาสตร์ทดสอบสมมติฐานของเธอ" },
  { en:"Imply", th:"บอกเป็นนัย", ex:"What are you implying?", ex_th:"คุณกำลังสื่อเป็นนัยว่าอะไร" },
  { en:"Infer", th:"อนุมาน", ex:"We can infer meaning from context.", ex_th:"เราสามารถอนุมานความหมายจากบริบทได้" },
  { en:"Interpret", th:"ตีความ", ex:"How do you interpret this poem?", ex_th:"คุณตีความบทกวีนี้อย่างไร" },
  { en:"Justify", th:"อ้างเหตุผล", ex:"Can you justify your decision?", ex_th:"คุณอ้างเหตุผลในการตัดสินใจได้ไหม" },
  { en:"Logic", th:"ตรรกะ", ex:"Her argument lacks logic.", ex_th:"ข้อโต้แย้งของเธอขาดตรรกะ" },
  { en:"Objective", th:"วัตถุประสงค์ / เป็นกลาง", ex:"Try to be objective.", ex_th:"พยายามเป็นกลาง" },
  { en:"Perspective", th:"มุมมอง", ex:"Let's look at it from a different perspective.", ex_th:"ลองมองจากมุมมองอื่น" },
  { en:"Relevant", th:"เกี่ยวข้อง", ex:"Is this information relevant?", ex_th:"ข้อมูลนี้เกี่ยวข้องไหม" },
  { en:"Summarize", th:"สรุป", ex:"Can you summarize the article?", ex_th:"ช่วยสรุปบทความหน่อย" },
  { en:"Synthesize", th:"สังเคราะห์", ex:"We must synthesize all the data.", ex_th:"เราต้องสังเคราะห์ข้อมูลทั้งหมด" },
  { en:"Valid", th:"มีเหตุผล / ถูกต้อง", ex:"That's a valid point.", ex_th:"นั่นเป็นประเด็นที่สมเหตุสมผล" },
  { en:"Acquire", th:"ได้รับ, ได้มา", ex:"She acquired a new skill.", ex_th:"เธอได้รับทักษะใหม่" },
{ en:"Adapt", th:"ปรับตัว", ex:"Animals adapt to their environment.", ex_th:"สัตว์ปรับตัวเข้ากับสภาพแวดล้อม" },
{ en:"Adequate", th:"เพียงพอ", ex:"The facilities are adequate.", ex_th:"สิ่งอำนวยความสะดวกเพียงพอ" },
{ en:"Ambition", th:"ความทะเยอทะยาน", ex:"He has great ambition.", ex_th:"เขามีความทะเยอทะยานสูง" },
{ en:"Anticipate", th:"คาดการณ์", ex:"We anticipate a rise in sales.", ex_th:"เราคาดการณ์ว่ายอดขายจะเพิ่มขึ้น" },
{ en:"Anxiety", th:"ความวิตกกังวล", ex:"She suffers from anxiety.", ex_th:"เธอทนทุกข์จากความวิตกกังวล" },
{ en:"Appreciate", th:"ชื่นชม, เห็นคุณค่า", ex:"I appreciate your help.", ex_th:"ฉันซาบซึ้งในความช่วยเหลือของคุณ" },
{ en:"Approach", th:"แนวทาง, เข้าหา", ex:"We need a new approach.", ex_th:"เราต้องการแนวทางใหม่" },
{ en:"Arouse", th:"กระตุ้น", ex:"The article aroused interest.", ex_th:"บทความกระตุ้นความสนใจ" },
{ en:"Aspect", th:"แง่มุม", ex:"Consider every aspect.", ex_th:"พิจารณาทุกแง่มุม" },
{ en:"Assert", th:"ยืนยัน", ex:"He asserted his innocence.", ex_th:"เขายืนยันความบริสุทธิ์ของเขา" },
{ en:"Attribute", th:"คุณลักษณะ, ถือว่าเป็นของ", ex:"Patience is a key attribute.", ex_th:"ความอดทนเป็นคุณลักษณะสำคัญ" },
{ en:"Absorb", th:"ดูดซับ, ซึมซับ", ex:"Plants absorb sunlight.", ex_th:"พืชดูดซับแสงแดด" },
{ en:"Abstract", th:"นามธรรม", ex:"The concept is too abstract.", ex_th:"แนวคิดนี้เป็นนามธรรมเกินไป" },
{ en:"Accumulate", th:"สะสม", ex:"Dust accumulates on the shelf.", ex_th:"ฝุ่นสะสมบนชั้นวาง" },
{ en:"Achieve", th:"บรรลุ", ex:"She achieved her goal.", ex_th:"เธอบรรลุเป้าหมาย" },
{ en:"Adjust", th:"ปรับ", ex:"I need to adjust the volume.", ex_th:"ฉันต้องปรับระดับเสียง" },
{ en:"Advance", th:"ก้าวหน้า, รุดหน้า", ex:"Technology continues to advance.", ex_th:"เทคโนโลยีเดินหน้าก้าวหน้าต่อไป" },
{ en:"Adopt", th:"นำมาใช้, รับเลี้ยง", ex:"They decided to adopt a child.", ex_th:"พวกเขาตัดสินใจรับเลี้ยงเด็ก" },
{ en:"Aggregate", th:"รวม, ผลรวม", ex:"The aggregate score is calculated.", ex_th:"คะแนนรวมถูกคำนวณแล้ว" },
{ en:"Aid", th:"ช่วยเหลือ", ex:"The charity provides aid to refugees.", ex_th:"องค์กรการกุศลให้ความช่วยเหลือผู้ลี้ภัย" },
{ en:"Alter", th:"เปลี่ยนแปลง", ex:"We had to alter our plans.", ex_th:"เราต้องเปลี่ยนแปลงแผนของเรา" },
{ en:"Ample", th:"เพียงพอ, มากมาย", ex:"There is ample time to finish.", ex_th:"มีเวลาเพียงพอที่จะทำเสร็จ" },
{ en:"Annual", th:"ประจำปี", ex:"The annual festival is in June.", ex_th:"เทศกาลประจำปีจัดในเดือนมิถุนายน" },
{ en:"Appoint", th:"แต่งตั้ง", ex:"They appointed a new manager.", ex_th:"พวกเขาแต่งตั้งผู้จัดการคนใหม่" },
{ en:"Apply", th:"นำไปใช้, สมัคร", ex:"She applied for a scholarship.", ex_th:"เธอสมัครขอทุนการศึกษา" },
{ en:"Assign", th:"มอบหมาย", ex:"The teacher assigned homework.", ex_th:"ครูมอบหมายการบ้าน" },
{ en:"Assist", th:"ช่วยเหลือ", ex:"Can you assist me with this?", ex_th:"คุณช่วยฉันเรื่องนี้ได้ไหม" },
{ en:"Attempt", th:"พยายาม", ex:"He attempted to break the record.", ex_th:"เขาพยายามทำลายสถิติ" },
{ en:"Attract", th:"ดึงดูด", ex:"The city attracts many tourists.", ex_th:"เมืองนี้ดึงดูดนักท่องเที่ยวจำนวนมาก" },
{ en:"Authorize", th:"อนุญาต", ex:"The manager authorized the payment.", ex_th:"ผู้จัดการอนุญาตการจ่ายเงิน" },
{ en:"Available", th:"มีอยู่, พร้อมใช้งาน", ex:"Is this seat available?", ex_th:"ที่นั่งนี้ว่างไหม" },
{ en:"Avoid", th:"หลีกเลี่ยง", ex:"Avoid eating too much sugar.", ex_th:"หลีกเลี่ยงการกินน้ำตาลมากเกินไป" },
{ en:"Aware", th:"ตระหนักรู้", ex:"Are you aware of the risks?", ex_th:"คุณตระหนักถึงความเสี่ยงไหม" },
{ en:"Barrier", th:"อุปสรรค", ex:"Language can be a barrier.", ex_th:"ภาษาอาจเป็นอุปสรรค" },
{ en:"Boast", th:"คุยโว", ex:"He boasts about his achievements.", ex_th:"เขาคุยโวเกี่ยวกับความสำเร็จของเขา" },
{ en:"Burden", th:"ภาระ", ex:"The debt was a heavy burden.", ex_th:"หนี้สินเป็นภาระหนัก" },
{ en:"Claim", th:"กล่าวอ้าง", ex:"She claims to be an expert.", ex_th:"เธออ้างว่าเป็นผู้เชี่ยวชาญ" },
{ en:"Compel", th:"บังคับ", ex:"The situation compelled him to act.", ex_th:"สถานการณ์บังคับให้เขาลงมือ" },
{ en:"Complex", th:"ซับซ้อน", ex:"The problem is complex.", ex_th:"ปัญหานี้ซับซ้อน" },
{ en:"Conduct", th:"ดำเนินการ, ความประพฤติ", ex:"We will conduct a survey.", ex_th:"เราจะดำเนินการสำรวจ" },
{ en:"Confine", th:"จำกัด", ex:"The discussion was confined to one topic.", ex_th:"การอภิปรายถูกจำกัดอยู่แค่หัวข้อเดียว" },
{ en:"Confirm", th:"ยืนยัน", ex:"Can you confirm the date?", ex_th:"คุณยืนยันวันที่ได้ไหม" },
{ en:"Confront", th:"เผชิญหน้า", ex:"She confronted her fears.", ex_th:"เธอเผชิญหน้ากับความกลัว" },
{ en:"Conscious", th:"รู้ตัว, ตระหนัก", ex:"He was conscious of the danger.", ex_th:"เขารู้ตัวถึงอันตราย" },
{ en:"Consent", th:"ความยินยอม", ex:"You need parental consent.", ex_th:"คุณต้องได้รับความยินยอมจากผู้ปกครอง" },
{ en:"Constitute", th:"ประกอบเป็น", ex:"Women constitute 50% of the workforce.", ex_th:"ผู้หญิงประกอบเป็น 50% ของแรงงาน" },
{ en:"Consult", th:"ปรึกษา", ex:"Consult your doctor first.", ex_th:"ปรึกษาแพทย์ก่อน" },
{ en:"Contemplate", th:"พิจารณาอย่างถี่ถ้วน", ex:"She contemplated the offer.", ex_th:"เธอพิจารณาข้อเสนอ" },
{ en:"Contemporary", th:"ร่วมสมัย", ex:"Contemporary art is diverse.", ex_th:"ศิลปะร่วมสมัยหลากหลาย" },
{ en:"Contract", th:"สัญญา, หดตัว", ex:"They signed a contract.", ex_th:"พวกเขาลงนามในสัญญา" },
{ en:"Controversial", th:"เป็นที่ถกเถียง", ex:"The topic is controversial.", ex_th:"หัวข้อนี้เป็นที่ถกเถียง" },
{ en:"Coordinate", th:"ประสานงาน", ex:"We need to coordinate efforts.", ex_th:"เราต้องประสานความพยายาม" },
{ en:"Core", th:"แกนกลาง", ex:"The core issue is trust.", ex_th:"ปัญหาหลักคือความไว้ใจ" },
{ en:"Correspond", th:"สอดคล้อง, ติดต่อทางจดหมาย", ex:"The results correspond to the theory.", ex_th:"ผลลัพธ์สอดคล้องกับทฤษฎี" },
{ en:"Crucial", th:"สำคัญอย่างยิ่ง", ex:"This decision is crucial.", ex_th:"การตัดสินใจนี้สำคัญอย่างยิ่ง" },
{ en:"Debate", th:"การอภิปราย", ex:"The debate was heated.", ex_th:"การอภิปรายดุเดือด" },
{ en:"Decade", th:"ทศวรรษ", ex:"A decade has passed.", ex_th:"หนึ่งทศวรรษผ่านไป" },
{ en:"Decline", th:"ลดลง, ปฏิเสธ", ex:"Sales declined last quarter.", ex_th:"ยอดขายลดลงไตรมาสที่แล้ว" },
{ en:"Define", th:"กำหนด, ให้คำจำกัดความ", ex:"How do you define success?", ex_th:"คุณนิยามความสำเร็จอย่างไร" },
{ en:"Demonstrate", th:"แสดงให้เห็น", ex:"She demonstrated the technique.", ex_th:"เธอสาธิตเทคนิค" },
{ en:"Deny", th:"ปฏิเสธ", ex:"He denied the allegation.", ex_th:"เขาปฏิเสธข้อกล่าวหา" },
{ en:"Depict", th:"พรรณนา, แสดงภาพ", ex:"The painting depicts a landscape.", ex_th:"ภาพวาดแสดงทิวทัศน์" },
{ en:"Derive", th:"ได้รับจาก", ex:"The word derives from Latin.", ex_th:"คำนี้มาจากภาษาละติน" },
{ en:"Desire", th:"ความปรารถนา", ex:"She has a desire to learn.", ex_th:"เธอมีความปรารถนาที่จะเรียนรู้" },
{ en:"Detect", th:"ตรวจพบ", ex:"The sensor detects movement.", ex_th:"เซนเซอร์ตรวจจับการเคลื่อนไหว" },
{ en:"Device", th:"อุปกรณ์", ex:"This device is portable.", ex_th:"อุปกรณ์นี้พกพาได้" },
{ en:"Devote", th:"อุทิศ", ex:"He devotes his time to charity.", ex_th:"เขาอุทิศเวลาให้การกุศล" },
{ en:"Dimension", th:"มิติ", ex:"We added another dimension.", ex_th:"เราเพิ่มอีกมิติหนึ่ง" },
{ en:"Diminish", th:"ลดลง", ex:"The pain diminished over time.", ex_th:"ความเจ็บปวดลดลงตามเวลา" },
{ en:"Disclose", th:"เปิดเผย", ex:"He disclosed the secret.", ex_th:"เขาเปิดเผยความลับ" },
{ en:"Dispute", th:"ข้อโต้แย้ง", ex:"They settled the dispute.", ex_th:"พวกเขายุติข้อโต้แย้ง" },
{ en:"Association", th:"สมาคม, องค์กร", ex:"She joined the student association.", ex_th:"เธอเข้าร่วมสมาคมนักศึกษา" },
{ en:"Institution", th:"สถาบัน", ex:"Harvard is a prestigious institution.", ex_th:"ฮาร์วาร์ดเป็นสถาบันที่มีชื่อเสียง" },
{ en:"Capable", th:"มีความสามารถ", ex:"He is capable of solving the problem.", ex_th:"เขามีความสามารถในการแก้ปัญหา" },
{ en:"Weakness", th:"ความอ่อนแอ", ex:"Lack of experience is his main weakness.", ex_th:"การขาดประสบการณ์คือจุดอ่อนหลักของเขา" },
{ en:"Strength", th:"ความแข็งแกร่ง", ex:"Her strength is communication.", ex_th:"จุดแข็งของเธอคือการสื่อสาร" },
{ en:"Award", th:"รางวัล", ex:"She received an award for her research.", ex_th:"เธอได้รับรางวัลจากงานวิจัยของเธอ" },
{ en:"Competitive", th:"การแข่งขัน", ex:"The market is highly competitive.", ex_th:"ตลาดมีการแข่งขันสูง" },
{ en:"Intention", th:"เป้าหมาย", ex:"My intention is to study abroad.", ex_th:"เป้าหมายของฉันคือไปเรียนต่างประเทศ" },
{ en:"Cope", th:"รับมือ", ex:"She can't cope with the pressure.", ex_th:"เธอรับมือกับความกดดันไม่ไหว" },
{ en:"Assume", th:"สมมุติ", ex:"I assume you're right.", ex_th:"ฉันสมมุติว่าคุณถูก" },
{ en:"Behalf", th:"ตัวแทน", ex:"I'm speaking on behalf of the team.", ex_th:"ฉันพูดในนามของทีม" },
{ en:"Commit", th:"ให้สัญญา", ex:"He committed to finishing the project.", ex_th:"เขาให้สัญญาว่าจะทำโปรเจกต์ให้เสร็จ" },
{ en:"Respond", th:"ตอบกลับ", ex:"Please respond to my email.", ex_th:"กรุณาตอบกลับอีเมลของฉัน" },
{ en:"Sufficient", th:"เพียงพอ", ex:"We have sufficient food.", ex_th:"เรามีอาหารเพียงพอ" },
{ en:"Tough", th:"ทนทาน", ex:"This material is tough and durable.", ex_th:"วัสดุนี้ทนทานและคงทน" },
{ en:"Abandon", th:"ละทิ้ง", ex:"They abandoned the old house.", ex_th:"พวกเขาละทิ้งบ้านหลังเก่า" },
{ en:"Betray", th:"ทรยศ", ex:"He betrayed his friend's trust.", ex_th:"เขาทรยศต่อความไว้ใจของเพื่อน" },
{ en:"Collapse", th:"ทรุดตัว", ex:"The bridge collapsed in the storm.", ex_th:"สะพานทรุดตัวลงในพายุ" },
{ en:"Cccur", th:"เกิดขึ้น", ex:"Accidents often occur at this intersection.", ex_th:"อุบัติเหตุมักเกิดขึ้นที่ทางแยกนี้" },
{ en:"Encounter", th:"การพบกัน", ex:"We had a brief encounter.", ex_th:"เรามีการพบกันสั้นๆ" },
{ en:"Combination", th:"การผสมผสาน", ex:"The dish is a combination of flavors.", ex_th:"จานนี้คือการผสมผสานของรสชาติ" },
{ en:"Reputation", th:"ชื่อเสียง", ex:"The company has a good reputation.", ex_th:"บริษัทมีชื่อเสียงดี" },
{ en:"Suspicious", th:"ขี้ระแวง", ex:"He looked suspicious.", ex_th:"เขาดูน่าสงสัย" },
{ en:"Outstanding", th:"โดดเด่น", ex:"She gave an outstanding performance.", ex_th:"เธอแสดงได้โดดเด่น" },
{ en:"Overall", th:"ทั้งหมด", ex:"The overall cost is $100.", ex_th:"ค่าใช้จ่ายทั้งหมดคือ 100 ดอลลาร์" },
{ en:"Truly", th:"อย่างแท้จริง", ex:"I am truly sorry.", ex_th:"ฉันเสียใจอย่างแท้จริง" },
{ en:"Initially", th:"ในขั้นแรก", ex:"Initially, I was nervous.", ex_th:"ในขั้นแรก ฉันรู้สึกประหม่า" },
{ en:"Deliberate", th:"คิดรอบคอบ", ex:"We need to deliberate before deciding.", ex_th:"เราต้องคิดรอบคอบก่อนตัดสินใจ" },
{ en:"Ideal", th:"อุดมคติ", ex:"Equality is an ideal we strive for.", ex_th:"ความเท่าเทียมคืออุดมคติที่เรามุ่งมั่น" },
{ en:"Relief", th:"ความโล่งอก", ex:"She felt relief after the exam.", ex_th:"เธอรู้สึกโล่งอกหลังจากสอบ" },
{ en:"Selection", th:"การคัดเลือก", ex:"The selection of candidates is tough.", ex_th:"การคัดเลือกผู้สมัครนั้นยาก" },
  { en:"Accelerate", th:"เร่งขึ้น", ex:"They want to accelerate the process.", ex_th:"พวกเขาต้องการเร่งกระบวนการ" },
  { en:"Biodiversity", th:"ความหลากหลายทางชีวภาพ", ex:"We must protect biodiversity.", ex_th:"เราต้องปกป้องความหลากหลายทางชีวภาพ" },
  { en:"Capitalism", th:"ระบบทุนนิยม", ex:"Capitalism encourages competition.", ex_th:"ทุนนิยมส่งเสริมการแข่งขัน" },
  { en:"Carbon", th:"คาร์บอน", ex:"Carbon dioxide causes global warming.", ex_th:"คาร์บอนไดออกไซด์ทำให้โลกร้อน" },
  { en:"Civilization", th:"อารยธรรม", ex:"Ancient civilizations fascinate me.", ex_th:"อารยธรรมโบราณทำให้ฉันหลงใหล" },
  { en:"Collaborate", th:"ร่วมมือ", ex:"We collaborate with local partners.", ex_th:"เราร่วมมือกับพันธมิตรในท้องถิ่น" },
  { en:"Conflict", th:"ความขัดแย้ง", ex:"The two countries are in conflict.", ex_th:"ทั้งสองประเทศกำลังขัดแย้งกัน" },
  { en:"Conservation", th:"การอนุรักษ์", ex:"Wildlife conservation is important.", ex_th:"การอนุรักษ์สัตว์ป่าสำคัญ" },
  { en:"Crisis", th:"วิกฤต", ex:"We are facing a climate crisis.", ex_th:"เรากำลังเผชิญวิกฤตสภาพภูมิอากาศ" },
  { en:"Culture", th:"วัฒนธรรม", ex:"Thai culture is unique.", ex_th:"วัฒนธรรมไทยมีเอกลักษณ์" },
  { en:"Democracy", th:"ประชาธิปไตย", ex:"Democracy gives people a voice.", ex_th:"ประชาธิปไตยให้สิทธิ์แก่ประชาชน" },
  { en:"Discrimination", th:"การเลือกปฏิบัติ", ex:"Discrimination is illegal.", ex_th:"การเลือกปฏิบัติเป็นสิ่งผิดกฎหมาย" },
  { en:"Diverse", th:"หลากหลาย", ex:"The city is very diverse.", ex_th:"เมืองนี้มีความหลากหลายมาก" },
  { en:"Ecosystem", th:"ระบบนิเวศ", ex:"The ecosystem is fragile.", ex_th:"ระบบนิเวศเปราะบาง" },
  { en:"Emission", th:"การปล่อย (ก๊าซ)", ex:"Car emissions pollute the air.", ex_th:"ไอเสียรถยนต์ทำให้อากาศเสีย" },
  { en:"Exploit", th:"ใช้ประโยชน์ / ขูดรีด", ex:"They exploit natural resources.", ex_th:"พวกเขาใช้ทรัพยากรธรรมชาติ" },
  { en:"Globalization", th:"โลกาภิวัตน์", ex:"Globalization connects the world.", ex_th:"โลกาภิวัตน์เชื่อมโลก" },
  { en:"Habitat", th:"ถิ่นที่อยู่", ex:"The panda's habitat is shrinking.", ex_th:"ถิ่นที่อยู่ของแพนด้ากำลังเล็กลง" },
  { en:"Inequality", th:"ความไม่เท่าเทียม", ex:"Income inequality is a problem.", ex_th:"ความเหลื่อมล้ำรายได้เป็นปัญหา" },
  { en:"Infrastructure", th:"โครงสร้างพื้นฐาน", ex:"We need better infrastructure.", ex_th:"เราต้องการโครงสร้างพื้นฐานที่ดีขึ้น" },
  { en:"Migrate", th:"อพยพ", ex:"Birds migrate south in winter.", ex_th:"นกอพยพลงใต้ในฤดูหนาว" },
  { en:"Poverty", th:"ความยากจน", ex:"Many people live in poverty.", ex_th:"หลายคนอาศัยอยู่ในความยากจน" },
  { en:"Renewable", th:"หมุนเวียนได้", ex:"Solar energy is renewable.", ex_th:"พลังงานแสงอาทิตย์หมุนเวียนได้" },
  { en:"Sustainable", th:"ยั่งยืน", ex:"We need sustainable solutions.", ex_th:"เราต้องการวิธีแก้ปัญหาที่ยั่งยืน" },
  { en:"Urbanize", th:"กลายเป็นเมือง", ex:"The area is urbanizing quickly.", ex_th:"พื้นที่นี้กลายเป็นเมืองอย่างรวดเร็ว" },

  { en:"Algorithm", th:"ขั้นตอนวิธี", ex:"Algorithms power search engines.", ex_th:"อัลกอริทึมขับเคลื่อนเครื่องมือค้นหา" },
  { en:"Artificial", th:"เทียม / ประดิษฐ์", ex:"Artificial intelligence is advancing.", ex_th:"ปัญญาประดิษฐ์กำลังก้าวหน้า" },
  { en:"Automate", th:"ทำให้อัตโนมัติ", ex:"We automate routine tasks.", ex_th:"เราทำงานประจำให้อัตโนมัติ" },
  { en:"Innovate", th:"คิดค้นสิ่งใหม่", ex:"Companies must innovate to survive.", ex_th:"บริษัทต้องคิดค้นสิ่งใหม่เพื่ออยู่รอด" },
  { en:"Mechanism", th:"กลไก", ex:"The mechanism is complex.", ex_th:"กลไกนี้ซับซ้อน" },
  { en:"Modify", th:"ดัดแปลง", ex:"We can modify the design.", ex_th:"เราสามารถดัดแปลงดีไซน์ได้" },
  { en:"Phenomenon", th:"ปรากฏการณ์", ex:"It's a natural phenomenon.", ex_th:"มันเป็นปรากฏการณ์ธรรมชาติ" },
  { en:"Prototype", th:"ต้นแบบ", ex:"They built a prototype.", ex_th:"พวกเขาสร้างต้นแบบ" },
  { en:"Simulate", th:"จำลอง", ex:"The program simulates real conditions.", ex_th:"โปรแกรมจำลองสถานการณ์จริง" },
  { en:"Technology", th:"เทคโนโลยี", ex:"Technology changes our lives.", ex_th:"เทคโนโลยีเปลี่ยนชีวิตเรา" },
{ en:"Acknowledge", th:"ยอมรับ, รับรู้", ex:"She acknowledged her mistake.", ex_th:"เธอยอมรับความผิดพลาดของเธอ" },
{ en:"Affect", th:"ส่งผลกระทบ", ex:"The weather affects my mood.", ex_th:"สภาพอากาศส่งผลต่ออารมณ์ของฉัน" },
{ en:"Alternative", th:"ทางเลือก", ex:"We need an alternative plan.", ex_th:"เราต้องการแผนสำรอง" },
{ en:"Apparent", th:"ชัดเจน, ปรากฏชัด", ex:"It became apparent that he was lying.", ex_th:"มันชัดเจนว่าเขากำลังโกหก" },
{ en:"Appropriate", th:"เหมาะสม", ex:"Is this appropriate for the occasion?", ex_th:"สิ่งนี้เหมาะสมกับโอกาสไหม" },
{ en:"Aspect", th:"แง่มุม", ex:"We considered every aspect of the problem.", ex_th:"เราพิจารณาทุกแง่มุมของปัญหา" },
{ en:"Consequence", th:"ผลที่ตามมา", ex:"He suffered the consequences of his actions.", ex_th:"เขาได้รับผลจากการกระทำของเขา" },
{ en:"Considerable", th:"มาก, สำคัญ", ex:"She has considerable experience.", ex_th:"เธอมีประสบการณ์มาก" },
{ en:"Consistent", th:"สม่ำเสมอ", ex:"His performance is consistent.", ex_th:"ผลงานของเขาสม่ำเสมอ" },
{ en:"Consume", th:"บริโภค", ex:"We consume too much sugar.", ex_th:"เราบริโภคน้ำตาลมากเกินไป" },
{ en:"Contrast", th:"ความแตกต่าง, ตรงกันข้าม", ex:"In contrast to last year, sales increased.", ex_th:"ตรงกันข้ามกับปีที่แล้ว ยอดขายเพิ่มขึ้น" },
{ en:"Contribute", th:"มีส่วนร่วม, สนับสนุน", ex:"Everyone can contribute to the project.", ex_th:"ทุกคนสามารถมีส่วนร่วมในโครงการได้" },
{ en:"Convenient", th:"สะดวก", ex:"Online shopping is very convenient.", ex_th:"การช้อปปิ้งออนไลน์สะดวกมาก" },
{ en:"Convey", th:"ถ่ายทอด, สื่อ", ex:"She conveyed her ideas clearly.", ex_th:"เธอถ่ายทอดแนวคิดของเธออย่างชัดเจน" },
{ en:"Convince", th:"โน้มน้าว", ex:"He convinced me to join the team.", ex_th:"เขาโน้มน้าวให้ฉันเข้าร่วมทีม" },
{ en:"Distinguish", th:"แยกแยะ", ex:"Can you distinguish between the two?", ex_th:"คุณแยกแยะระหว่างสองสิ่งนี้ได้ไหม" },
{ en:"Dominate", th:"มีอำนาจเหนือ", ex:"The company dominates the market.", ex_th:"บริษัทมีอำนาจเหนือตลาด" },
{ en:"Eliminate", th:"กำจัด", ex:"We need to eliminate errors.", ex_th:"เราต้องกำจัดข้อผิดพลาด" },
{ en:"Emerge", th:"ปรากฏขึ้น", ex:"New trends emerge every year.", ex_th:"เทรนด์ใหม่ๆ ปรากฏขึ้นทุกปี" },
{ en:"Enable", th:"ทำให้สามารถ", ex:"Technology enables remote work.", ex_th:"เทคโนโลยีทำให้การทำงานทางไกลเป็นไปได้" },
{ en:"Ensure", th:"ทำให้แน่ใจ", ex:"Please ensure the door is locked.", ex_th:"กรุณาทำให้แน่ใจว่าประตูล็อกแล้ว" },
{ en:"Evaluate", th:"ประเมิน", ex:"We must evaluate the risks.", ex_th:"เราต้องประเมินความเสี่ยง" },
{ en:"Eventually", th:"ในที่สุด", ex:"Eventually, she agreed to help.", ex_th:"ในที่สุด เธอก็ตกลงช่วย" },
{ en:"Expand", th:"ขยาย", ex:"The business expanded rapidly.", ex_th:"ธุรกิจขยายตัวอย่างรวดเร็ว" },
{ en:"Expert", th:"ผู้เชี่ยวชาญ", ex:"He is an expert in robotics.", ex_th:"เขาเป็นผู้เชี่ยวชาญด้านหุ่นยนต์" },
{ en:"Factor", th:"ปัจจัย", ex:"Price is an important factor.", ex_th:"ราคาเป็นปัจจัยสำคัญ" },
{ en:"Feature", th:"ลักษณะเด่น", ex:"The phone has many new features.", ex_th:"โทรศัพท์มีคุณสมบัติใหม่มากมาย" },
{ en:"Focus", th:"จุดสนใจ", ex:"Let's focus on the main issue.", ex_th:"มาโฟกัสที่ประเด็นหลักกัน" },
{ en:"Function", th:"หน้าที่", ex:"What is the function of this button?", ex_th:"ปุ่มนี้มีหน้าที่อะไร" },
{ en:"Furthermore", th:"นอกจากนี้", ex:"Furthermore, the cost is too high.", ex_th:"นอกจากนี้ ค่าใช้จ่ายยังสูงเกินไป" },
];