const VOCAB_BANK = [
  { en:"Ambiguous", th:"มีความหมายไม่ชัดเจน", ex:"The instructions were ambiguous.", ex_th:"คำแนะนำกำกวม" },
  { en:"Analogy", th:"การเปรียบเทียบ", ex:"He drew an analogy between a heart and a pump.", ex_th:"เขาเปรียบเทียบหัวใจกับปั๊ม" },
  { en:"Analyze", th:"วิเคราะห์", ex:"We need to analyze the data carefully.", ex_th:"เราต้องวิเคราะห์ข้อมูลอย่างรอบคอบ" },
  { en:"Advocate", th:"สนับสนุน / ผู้สนับสนุน", ex:"She is a strong advocate for education.", ex_th:"เธอเป็นผู้สนับสนุนด้านการศึกษาอย่างแรงกล้า" },
  { en:"Assess", th:"ประเมิน", ex:"The teacher will assess the students' progress.", ex_th:"ครูจะประเมินความก้าวหน้าของนักเรียน" },
  { en:"Assumption", th:"การสมมติฐาน", ex:"His theory is based on a false assumption.", ex_th:"ทฤษฎีของเขาอยู่บนสมมติฐานที่ผิด" },
  { en:"Bias", th:"อคติ", ex:"The article showed a clear bias.", ex_th:"บทความแสดงอคติอย่างชัดเจน" },
  { en:"Clarify", th:"ชี้แจง", ex:"Could you clarify your point?", ex_th:"ช่วยชี้แจงประเด็นของคุณหน่อยได้ไหม" },
  { en:"Coherent", th:"เชื่อมโยงกันอย่างสมเหตุสมผล", ex:"She gave a coherent explanation.", ex_th:"เธออธิบายได้สอดคล้องกัน" },
  { en:"Concept", th:"แนวคิด", ex:"It's a difficult concept to understand.", ex_th:"มันเป็นแนวคิดที่เข้าใจยาก" },
  { en:"Conclusion", th:"บทสรุป", ex:"What conclusion can we draw?", ex_th:"เราสรุปได้ว่าอะไร" },
  { en:"Context", th:"บริบท", ex:"You need to understand the context.", ex_th:"คุณต้องเข้าใจบริบท" },
  { en:"Contradict", th:"ขัดแย้ง", ex:"His statement contradicts the facts.", ex_th:"คำพูดของเขาขัดแย้งกับข้อเท็จจริง" },
  { en:"Criteria", th:"เกณฑ์", ex:"What are the selection criteria?", ex_th:"เกณฑ์การคัดเลือกคืออะไร" },
  { en:"Deduce", th:"สรุปหาเหตุผล", ex:"From the clues, we can deduce the answer.", ex_th:"จากเบาะแส เราอาจสรุปคำตอบได้" },
  { en:"Elaborate", th:"อธิบายอย่างละเอียด", ex:"Could you elaborate on that idea?", ex_th:"ช่วยอธิบายแนวคิดนั้นเพิ่มเติมได้ไหม" },
  { en:"Emphasize", th:"เน้น / ให้ความสำคัญ", ex:"I want to emphasize this point.", ex_th:"ฉันอยากเน้นประเด็นนี้" },
  { en:"Evidence", th:"หลักฐาน", ex:"There is no evidence to support that claim.", ex_th:"ไม่มีหลักฐานสนับสนุนคำกล่าวนั้น" },
  { en:"Explicit", th:"ชัดเจน / ตรงไปตรงมา", ex:"The instructions were explicit.", ex_th:"คำแนะนำชัดเจนดี" },
  { en:"Generalize", th:"สรุปอย่างกว้างๆ", ex:"You can't generalize from one example.", ex_th:"คุณไม่สามารถสรุปจากตัวอย่างเดียวได้" },
  { en:"Hypothesis", th:"สมมติฐาน", ex:"The scientist tested her hypothesis.", ex_th:"นักวิทยาศาสตร์ทดสอบสมมติฐานของเธอ" },
  { en:"Imply", th:"บอกเป็นนัย", ex:"What are you implying?", ex_th:"คุณกำลังสื่อเป็นนัยว่าอะไร" },
  { en:"Infer", th:"อนุมาน", ex:"We can infer meaning from context.", ex_th:"เราสามารถอนุมานความหมายจากบริบทได้" },
  { en:"Interpret", th:"ตีความ", ex:"How do you interpret this poem?", ex_th:"คุณตีความบทกวีนี้อย่างไร" },
  { en:"Justify", th:"อ้างเหตุผล", ex:"Can you justify your decision?", ex_th:"คุณอ้างเหตุผลในการตัดสินใจได้ไหม" },
  { en:"Logic", th:"ตรรกะ", ex:"Her argument lacks logic.", ex_th:"ข้อโต้แย้งของเธอขาดตรรกะ" },
  { en:"Objective", th:"วัตถุประสงค์ / เป็นกลาง", ex:"Try to be objective.", ex_th:"พยายามเป็นกลาง" },
  { en:"Perspective", th:"มุมมอง", ex:"Let's look at it from a different perspective.", ex_th:"ลองมองจากมุมมองอื่น" },
  { en:"Relevant", th:"เกี่ยวข้อง", ex:"Is this information relevant?", ex_th:"ข้อมูลนี้เกี่ยวข้องไหม" },
  { en:"Summarize", th:"สรุป", ex:"Can you summarize the article?", ex_th:"ช่วยสรุปบทความหน่อย" },
  { en:"Synthesize", th:"สังเคราะห์", ex:"We must synthesize all the data.", ex_th:"เราต้องสังเคราะห์ข้อมูลทั้งหมด" },
  { en:"Valid", th:"มีเหตุผล / ถูกต้อง", ex:"That's a valid point.", ex_th:"นั่นเป็นประเด็นที่สมเหตุสมผล" },
{ en:"Association", th:"สมาคม, องค์กร", ex:"She joined the student association.", ex_th:"เธอเข้าร่วมสมาคมนักศึกษา" },
{ en:"Institution", th:"สถาบัน", ex:"Harvard is a prestigious institution.", ex_th:"ฮาร์วาร์ดเป็นสถาบันที่มีชื่อเสียง" },
{ en:"Capable", th:"มีความสามารถ", ex:"He is capable of solving the problem.", ex_th:"เขามีความสามารถในการแก้ปัญหา" },
{ en:"Weakness", th:"ความอ่อนแอ", ex:"Lack of experience is his main weakness.", ex_th:"การขาดประสบการณ์คือจุดอ่อนหลักของเขา" },
{ en:"Strength", th:"ความแข็งแกร่ง", ex:"Her strength is communication.", ex_th:"จุดแข็งของเธอคือการสื่อสาร" },
{ en:"Award", th:"รางวัล", ex:"She received an award for her research.", ex_th:"เธอได้รับรางวัลจากงานวิจัยของเธอ" },
{ en:"Competitive", th:"การแข่งขัน", ex:"The market is highly competitive.", ex_th:"ตลาดมีการแข่งขันสูง" },
{ en:"Intention", th:"เป้าหมาย", ex:"My intention is to study abroad.", ex_th:"เป้าหมายของฉันคือไปเรียนต่างประเทศ" },
{ en:"Cope", th:"รับมือ", ex:"She can't cope with the pressure.", ex_th:"เธอรับมือกับความกดดันไม่ไหว" },
{ en:"Assume", th:"สมมุติ", ex:"I assume you're right.", ex_th:"ฉันสมมุติว่าคุณถูก" },
{ en:"Behalf", th:"ตัวแทน", ex:"I'm speaking on behalf of the team.", ex_th:"ฉันพูดในนามของทีม" },
{ en:"Commit", th:"ให้สัญญา", ex:"He committed to finishing the project.", ex_th:"เขาให้สัญญาว่าจะทำโปรเจกต์ให้เสร็จ" },
{ en:"Respond", th:"ตอบกลับ", ex:"Please respond to my email.", ex_th:"กรุณาตอบกลับอีเมลของฉัน" },
{ en:"Sufficient", th:"เพียงพอ", ex:"We have sufficient food.", ex_th:"เรามีอาหารเพียงพอ" },
{ en:"Tough", th:"ทนทาน", ex:"This material is tough and durable.", ex_th:"วัสดุนี้ทนทานและคงทน" },
{ en:"Abandon", th:"ละทิ้ง", ex:"They abandoned the old house.", ex_th:"พวกเขาละทิ้งบ้านหลังเก่า" },
{ en:"Betray", th:"ทรยศ", ex:"He betrayed his friend's trust.", ex_th:"เขาทรยศต่อความไว้ใจของเพื่อน" },
{ en:"Collapse", th:"ทรุดตัว", ex:"The bridge collapsed in the storm.", ex_th:"สะพานทรุดตัวลงในพายุ" },
{ en:"Cccur", th:"เกิดขึ้น", ex:"Accidents often occur at this intersection.", ex_th:"อุบัติเหตุมักเกิดขึ้นที่ทางแยกนี้" },
{ en:"Encounter", th:"การพบกัน", ex:"We had a brief encounter.", ex_th:"เรามีการพบกันสั้นๆ" },
{ en:"Combination", th:"การผสมผสาน", ex:"The dish is a combination of flavors.", ex_th:"จานนี้คือการผสมผสานของรสชาติ" },
{ en:"Reputation", th:"ชื่อเสียง", ex:"The company has a good reputation.", ex_th:"บริษัทมีชื่อเสียงดี" },
{ en:"Suspicious", th:"ขี้ระแวง", ex:"He looked suspicious.", ex_th:"เขาดูน่าสงสัย" },
{ en:"Outstanding", th:"โดดเด่น", ex:"She gave an outstanding performance.", ex_th:"เธอแสดงได้โดดเด่น" },
{ en:"Overall", th:"ทั้งหมด", ex:"The overall cost is $100.", ex_th:"ค่าใช้จ่ายทั้งหมดคือ 100 ดอลลาร์" },
{ en:"Truly", th:"อย่างแท้จริง", ex:"I am truly sorry.", ex_th:"ฉันเสียใจอย่างแท้จริง" },
{ en:"Initially", th:"ในขั้นแรก", ex:"Initially, I was nervous.", ex_th:"ในขั้นแรก ฉันรู้สึกประหม่า" },
{ en:"Deliberate", th:"คิดรอบคอบ", ex:"We need to deliberate before deciding.", ex_th:"เราต้องคิดรอบคอบก่อนตัดสินใจ" },
{ en:"Ideal", th:"อุดมคติ", ex:"Equality is an ideal we strive for.", ex_th:"ความเท่าเทียมคืออุดมคติที่เรามุ่งมั่น" },
{ en:"Relief", th:"ความโล่งอก", ex:"She felt relief after the exam.", ex_th:"เธอรู้สึกโล่งอกหลังจากสอบ" },
{ en:"Selection", th:"การคัดเลือก", ex:"The selection of candidates is tough.", ex_th:"การคัดเลือกผู้สมัครนั้นยาก" },
  { en:"Accelerate", th:"เร่งขึ้น", ex:"They want to accelerate the process.", ex_th:"พวกเขาต้องการเร่งกระบวนการ" },
  { en:"Biodiversity", th:"ความหลากหลายทางชีวภาพ", ex:"We must protect biodiversity.", ex_th:"เราต้องปกป้องความหลากหลายทางชีวภาพ" },
  { en:"Capitalism", th:"ระบบทุนนิยม", ex:"Capitalism encourages competition.", ex_th:"ทุนนิยมส่งเสริมการแข่งขัน" },
  { en:"Carbon", th:"คาร์บอน", ex:"Carbon dioxide causes global warming.", ex_th:"คาร์บอนไดออกไซด์ทำให้โลกร้อน" },
  { en:"Civilization", th:"อารยธรรม", ex:"Ancient civilizations fascinate me.", ex_th:"อารยธรรมโบราณทำให้ฉันหลงใหล" },
  { en:"Collaborate", th:"ร่วมมือ", ex:"We collaborate with local partners.", ex_th:"เราร่วมมือกับพันธมิตรในท้องถิ่น" },
  { en:"Conflict", th:"ความขัดแย้ง", ex:"The two countries are in conflict.", ex_th:"ทั้งสองประเทศกำลังขัดแย้งกัน" },
  { en:"Conservation", th:"การอนุรักษ์", ex:"Wildlife conservation is important.", ex_th:"การอนุรักษ์สัตว์ป่าสำคัญ" },
  { en:"Crisis", th:"วิกฤต", ex:"We are facing a climate crisis.", ex_th:"เรากำลังเผชิญวิกฤตสภาพภูมิอากาศ" },
  { en:"Culture", th:"วัฒนธรรม", ex:"Thai culture is unique.", ex_th:"วัฒนธรรมไทยมีเอกลักษณ์" },
  { en:"Democracy", th:"ประชาธิปไตย", ex:"Democracy gives people a voice.", ex_th:"ประชาธิปไตยให้สิทธิ์แก่ประชาชน" },
  { en:"Discrimination", th:"การเลือกปฏิบัติ", ex:"Discrimination is illegal.", ex_th:"การเลือกปฏิบัติเป็นสิ่งผิดกฎหมาย" },
  { en:"Diverse", th:"หลากหลาย", ex:"The city is very diverse.", ex_th:"เมืองนี้มีความหลากหลายมาก" },
  { en:"Ecosystem", th:"ระบบนิเวศ", ex:"The ecosystem is fragile.", ex_th:"ระบบนิเวศเปราะบาง" },
  { en:"Emission", th:"การปล่อย (ก๊าซ)", ex:"Car emissions pollute the air.", ex_th:"ไอเสียรถยนต์ทำให้อากาศเสีย" },
  { en:"Exploit", th:"ใช้ประโยชน์ / ขูดรีด", ex:"They exploit natural resources.", ex_th:"พวกเขาใช้ทรัพยากรธรรมชาติ" },
  { en:"Globalization", th:"โลกาภิวัตน์", ex:"Globalization connects the world.", ex_th:"โลกาภิวัตน์เชื่อมโลก" },
  { en:"Habitat", th:"ถิ่นที่อยู่", ex:"The panda's habitat is shrinking.", ex_th:"ถิ่นที่อยู่ของแพนด้ากำลังเล็กลง" },
  { en:"Inequality", th:"ความไม่เท่าเทียม", ex:"Income inequality is a problem.", ex_th:"ความเหลื่อมล้ำรายได้เป็นปัญหา" },
  { en:"Infrastructure", th:"โครงสร้างพื้นฐาน", ex:"We need better infrastructure.", ex_th:"เราต้องการโครงสร้างพื้นฐานที่ดีขึ้น" },
  { en:"Migrate", th:"อพยพ", ex:"Birds migrate south in winter.", ex_th:"นกอพยพลงใต้ในฤดูหนาว" },
  { en:"Poverty", th:"ความยากจน", ex:"Many people live in poverty.", ex_th:"หลายคนอาศัยอยู่ในความยากจน" },
  { en:"Renewable", th:"หมุนเวียนได้", ex:"Solar energy is renewable.", ex_th:"พลังงานแสงอาทิตย์หมุนเวียนได้" },
  { en:"Sustainable", th:"ยั่งยืน", ex:"We need sustainable solutions.", ex_th:"เราต้องการวิธีแก้ปัญหาที่ยั่งยืน" },
  { en:"Urbanize", th:"กลายเป็นเมือง", ex:"The area is urbanizing quickly.", ex_th:"พื้นที่นี้กลายเป็นเมืองอย่างรวดเร็ว" },

  { en:"Algorithm", th:"ขั้นตอนวิธี", ex:"Algorithms power search engines.", ex_th:"อัลกอริทึมขับเคลื่อนเครื่องมือค้นหา" },
  { en:"Artificial", th:"เทียม / ประดิษฐ์", ex:"Artificial intelligence is advancing.", ex_th:"ปัญญาประดิษฐ์กำลังก้าวหน้า" },
  { en:"Automate", th:"ทำให้อัตโนมัติ", ex:"We automate routine tasks.", ex_th:"เราทำงานประจำให้อัตโนมัติ" },
  { en:"Innovate", th:"คิดค้นสิ่งใหม่", ex:"Companies must innovate to survive.", ex_th:"บริษัทต้องคิดค้นสิ่งใหม่เพื่ออยู่รอด" },
  { en:"Mechanism", th:"กลไก", ex:"The mechanism is complex.", ex_th:"กลไกนี้ซับซ้อน" },
  { en:"Modify", th:"ดัดแปลง", ex:"We can modify the design.", ex_th:"เราสามารถดัดแปลงดีไซน์ได้" },
  { en:"Phenomenon", th:"ปรากฏการณ์", ex:"It's a natural phenomenon.", ex_th:"มันเป็นปรากฏการณ์ธรรมชาติ" },
  { en:"Prototype", th:"ต้นแบบ", ex:"They built a prototype.", ex_th:"พวกเขาสร้างต้นแบบ" },
  { en:"Simulate", th:"จำลอง", ex:"The program simulates real conditions.", ex_th:"โปรแกรมจำลองสถานการณ์จริง" },
  { en:"Technology", th:"เทคโนโลยี", ex:"Technology changes our lives.", ex_th:"เทคโนโลยีเปลี่ยนชีวิตเรา" },
{ en:"Acknowledge", th:"ยอมรับ, รับรู้", ex:"She acknowledged her mistake.", ex_th:"เธอยอมรับความผิดพลาดของเธอ" },
{ en:"Affect", th:"ส่งผลกระทบ", ex:"The weather affects my mood.", ex_th:"สภาพอากาศส่งผลต่ออารมณ์ของฉัน" },
{ en:"Alternative", th:"ทางเลือก", ex:"We need an alternative plan.", ex_th:"เราต้องการแผนสำรอง" },
{ en:"Apparent", th:"ชัดเจน, ปรากฏชัด", ex:"It became apparent that he was lying.", ex_th:"มันชัดเจนว่าเขากำลังโกหก" },
{ en:"Appropriate", th:"เหมาะสม", ex:"Is this appropriate for the occasion?", ex_th:"สิ่งนี้เหมาะสมกับโอกาสไหม" },
{ en:"Aspect", th:"แง่มุม", ex:"We considered every aspect of the problem.", ex_th:"เราพิจารณาทุกแง่มุมของปัญหา" },
{ en:"Consequence", th:"ผลที่ตามมา", ex:"He suffered the consequences of his actions.", ex_th:"เขาได้รับผลจากการกระทำของเขา" },
{ en:"Considerable", th:"มาก, สำคัญ", ex:"She has considerable experience.", ex_th:"เธอมีประสบการณ์มาก" },
{ en:"Consistent", th:"สม่ำเสมอ", ex:"His performance is consistent.", ex_th:"ผลงานของเขาสม่ำเสมอ" },
{ en:"Consume", th:"บริโภค", ex:"We consume too much sugar.", ex_th:"เราบริโภคน้ำตาลมากเกินไป" },
{ en:"Contrast", th:"ความแตกต่าง, ตรงกันข้าม", ex:"In contrast to last year, sales increased.", ex_th:"ตรงกันข้ามกับปีที่แล้ว ยอดขายเพิ่มขึ้น" },
{ en:"Contribute", th:"มีส่วนร่วม, สนับสนุน", ex:"Everyone can contribute to the project.", ex_th:"ทุกคนสามารถมีส่วนร่วมในโครงการได้" },
{ en:"Convenient", th:"สะดวก", ex:"Online shopping is very convenient.", ex_th:"การช้อปปิ้งออนไลน์สะดวกมาก" },
{ en:"Convey", th:"ถ่ายทอด, สื่อ", ex:"She conveyed her ideas clearly.", ex_th:"เธอถ่ายทอดแนวคิดของเธออย่างชัดเจน" },
{ en:"Convince", th:"โน้มน้าว", ex:"He convinced me to join the team.", ex_th:"เขาโน้มน้าวให้ฉันเข้าร่วมทีม" },
{ en:"Distinguish", th:"แยกแยะ", ex:"Can you distinguish between the two?", ex_th:"คุณแยกแยะระหว่างสองสิ่งนี้ได้ไหม" },
{ en:"Dominate", th:"มีอำนาจเหนือ", ex:"The company dominates the market.", ex_th:"บริษัทมีอำนาจเหนือตลาด" },
{ en:"Eliminate", th:"กำจัด", ex:"We need to eliminate errors.", ex_th:"เราต้องกำจัดข้อผิดพลาด" },
{ en:"Emerge", th:"ปรากฏขึ้น", ex:"New trends emerge every year.", ex_th:"เทรนด์ใหม่ๆ ปรากฏขึ้นทุกปี" },
{ en:"Enable", th:"ทำให้สามารถ", ex:"Technology enables remote work.", ex_th:"เทคโนโลยีทำให้การทำงานทางไกลเป็นไปได้" },
{ en:"Ensure", th:"ทำให้แน่ใจ", ex:"Please ensure the door is locked.", ex_th:"กรุณาทำให้แน่ใจว่าประตูล็อกแล้ว" },
{ en:"Evaluate", th:"ประเมิน", ex:"We must evaluate the risks.", ex_th:"เราต้องประเมินความเสี่ยง" },
{ en:"Eventually", th:"ในที่สุด", ex:"Eventually, she agreed to help.", ex_th:"ในที่สุด เธอก็ตกลงช่วย" },
{ en:"Expand", th:"ขยาย", ex:"The business expanded rapidly.", ex_th:"ธุรกิจขยายตัวอย่างรวดเร็ว" },
{ en:"Expert", th:"ผู้เชี่ยวชาญ", ex:"He is an expert in robotics.", ex_th:"เขาเป็นผู้เชี่ยวชาญด้านหุ่นยนต์" },
{ en:"Factor", th:"ปัจจัย", ex:"Price is an important factor.", ex_th:"ราคาเป็นปัจจัยสำคัญ" },
{ en:"Feature", th:"ลักษณะเด่น", ex:"The phone has many new features.", ex_th:"โทรศัพท์มีคุณสมบัติใหม่มากมาย" },
{ en:"Focus", th:"จุดสนใจ", ex:"Let's focus on the main issue.", ex_th:"มาโฟกัสที่ประเด็นหลักกัน" },
{ en:"Function", th:"หน้าที่", ex:"What is the function of this button?", ex_th:"ปุ่มนี้มีหน้าที่อะไร" },
{ en:"Furthermore", th:"นอกจากนี้", ex:"Furthermore, the cost is too high.", ex_th:"นอกจากนี้ ค่าใช้จ่ายยังสูงเกินไป" },
];